3lang3/react-vant

package.json
src/image/index.tsx

解决当Image的src变化时loading没有被正确设置的问题。

fix: reset loading correctly when image src is changed

---

package.json
src/dropdown-menu/DropdownMenuItem.tsx
src/index-bar/IndexBar.tsx

将另外两个用到`renderToContainer`的地方补起来了。

feat: support ssr

---

src/calendar/PropsType.ts

修复Calendar 日历 的属性minDate、maxDate为可选值

fix(Calendar): fix Calendar option props

---

src/styles/README.md

docs(CSSTransition): add install CSSTransition step

---

src/picker/README.md

docs(Picker): remove duplicate props

---

src/stepper/README.md

docs(Stepper): update Stepper doc

---

src/rate/README.md

docs(Rate): update Rate docs

---

src/collapse/PropsType.ts

fix(Collapse): fix Collapse props

---

src/action-sheet/demo/index.tsx
src/action-sheet/demo/style.less
src/icon/PropsType.ts
src/icon/README.md
src/icon/createFromIconfontCN.tsx
src/icon/demo/index.tsx
src/icon/index.tsx

Icon add createFromIconfontCN method

feat: update Icon

---

src/password-input/style/index.less

- 修复密码输入框的宽度
- 重置input[type='number']的样式

fix(PasswordInput): fix input width & style

---

src/tag/README.md

docs(Tag): update Tag prop text-color

---

packages/react-vant/src/field/README.md

docs(Field):update docs

---

packages/react-vant/vant.config.js

docs: sort nav

---

packages/react-vant/src/search/PropsType.ts
packages/react-vant/src/search/Search.tsx
packages/react-vant/src/search/demo/index.tsx

fix: 补全Search组件事件

---

packages/react-vant/src/sidebar/Sidebar.tsx

fix(Sidebar): add defaultValue

---

packages/react-vant/src/dropdown-menu/DropdownMenu.tsx

fix(DropdownMenu): 修复 `style`和`className` 挂载

---

packages/react-vant/src/cell/CellGroup.tsx

feat(Cell): fix #147

---

packages/react-vant/docs/markdown/use-form-smart.zh-CN.md
packages/react-vant/vant.config.js

feat: add use-form-smart document

---

packages/react-vant/src/uploader/README.md

修正文档中关于uploader组件中beforeRead逻辑和ts语法

docs: 更新 uploader readme文档

---

packages/react-vant/src/card/Card.tsx
packages/react-vant/src/card/PropsType.ts
packages/react-vant/src/card/README.md

feat(components): `Card` 兼容商品价格不传小数部分

---

.github/workflows/issue-close-require.yml
.github/workflows/issue-labeled.yml

增加Issue Labeled 相关Github Action

chore(components): add GitHub action to handle label

---

packages/react-vant/src/password-input/PasswordInput.tsx

fix(password-input): 修复PasswordInput组件初始化报错

---

packages/react-vant/src/dropdown-menu/style/index.less

fix: DropdownMenu 勾选图标位置修复

---

packages/react-vant/src/calendar/Calendar.tsx

[bug]: calendar multiple unselected not update in time

---

packages/react-vant/src/components/image-preview/ImagePreview.tsx

fix: Iimage preview mask close

---

packages/react-vant/src/components/count-down/README.md
packages/react-vant/src/components/hooks/use-count-down.ts

fix: use-count-down onChange current value

---

packages/react-vant/src/components/picker/Picker.tsx
packages/react-vant/src/components/picker/PropsType.ts
packages/react-vant/src/components/picker/demo/cascader.tsx

feat: Picker add column type param

---

packages/react-vant/rcdoc.config.ts
packages/react-vant/src/components/floating-ball/FloatingBall.tsx
packages/react-vant/src/components/floating-ball/FloatingBallContext.ts
packages/react-vant/src/components/floating-ball/FloatingBallItem.tsx
packages/react-vant/src/components/floating-ball/PropsType.ts
packages/react-vant/src/components/floating-ball/README.md
packages/react-vant/src/components/floating-ball/demo/base.tsx
packages/react-vant/src/components/floating-ball/demo/bubble.tsx
packages/react-vant/src/components/floating-ball/demo/menu.tsx
packages/react-vant/src/components/floating-ball/demo/style.less
packages/react-vant/src/components/floating-ball/index.tsx
packages/react-vant/src/components/floating-ball/style/index.less
packages/react-vant/src/components/floating-ball/style/var.less
packages/react-vant/src/components/floating-ball/useFloatingTouch.ts
packages/react-vant/src/components/index.ts
packages/react-vant/src/components/utils/throttle.ts
packages/react-vant/src/index.ts

Adjust Pr 392

---

packages/react-vant/rcdoc.config.ts
packages/react-vant/src/components/floating-ball/FloatingBall.tsx
packages/react-vant/src/components/floating-ball/FloatingBallContext.ts
packages/react-vant/src/components/floating-ball/FloatingBallItem.tsx
packages/react-vant/src/components/floating-ball/PropsType.ts
packages/react-vant/src/components/floating-ball/README.md
packages/react-vant/src/components/floating-ball/demo/base.tsx
packages/react-vant/src/components/floating-ball/index.tsx
packages/react-vant/src/components/floating-ball/style/index.less
packages/react-vant/src/components/floating-ball/style/var.less
packages/react-vant/src/components/index.ts
packages/react-vant/src/index.ts

feat: add floating-ball

---

packages/react-vant/src/components/action-sheet/ActionSheet.tsx
packages/react-vant/src/components/action-sheet/demo/custom.tsx
packages/react-vant/src/components/action-sheet/style/index.less
packages/react-vant/src/components/dialog/PropsType.ts
packages/react-vant/src/components/image-preview/PropsType.ts
packages/react-vant/src/components/toast/Toast.tsx
packages/react-vant/src/components/toast/style/index.less

- toast
- action-sheet
correct image-preview & dialog types

fix: correct popup wrapper css order 

---

packages/react-vant/package.json
packages/react-vant/src/components/dialog/index.tsx
packages/react-vant/src/components/image-preview/index.tsx
packages/react-vant/src/components/notify/index.tsx
packages/react-vant/src/components/toast/index.tsx
packages/react-vant/src/components/utils/dom/render.ts
packages/react-vant/src/components/utils/dom/renderToBody.ts
packages/react-vant/src/components/utils/dom/renderToContainer.ts

Fix rc18 render

---

packages/react-vant/package.json
packages/react-vant/src/components/area/Area.tsx
packages/react-vant/src/components/area/demo/base.tsx
packages/react-vant/src/components/datetime-picker/DatePicker.tsx
packages/react-vant/src/components/datetime-picker/TimePicker.tsx
packages/react-vant/src/components/datetime-picker/demo/time.tsx
packages/react-vant/src/components/picker/Picker.tsx
packages/react-vant/src/components/picker/PickerColumn.tsx
packages/react-vant/src/components/picker/demo/cascader.tsx
packages/react-vant/src/components/utils/dom/render.ts
packages/react-vant/src/components/utils/dom/version.ts
packages/react-vant/src/components/utils/raf.ts

Fix rc18 raf

---

packages/react-vant/src/components/popup/Popup.tsx
packages/react-vant/src/components/popup/PropsType.ts
packages/react-vant/src/components/popup/README.md
packages/react-vant/src/components/popup/demo/teleport.tsx
packages/react-vant/src/components/popup/demo/title.tsx
packages/react-vant/src/components/popup/style/index.less
packages/react-vant/src/components/popup/style/var.less

- 修正了 `Popup` 组件中的单词拼写错误 https://github.com/3lang3/react-vant/issues/438#issue-1250670573
注意这涉及到API变更，请评估其影响

fix: misspelled word

---

packages/react-vant/src/components/uploader/demo/utils.ts

docs: 修复文档提示

---

packages/react-vant/src/components/input/Input.tsx
packages/react-vant/src/components/input/PropsType.ts
packages/react-vant/src/components/input/README.md
packages/react-vant/src/components/input/demo/base.tsx
packages/react-vant/src/components/input/style/index.less

feat: input 新增 `prefix` `suffix` 属性

---

packages/react-vant/src/components/rate/Rate.tsx
packages/react-vant/src/components/rate/style/index.less

fix: 修复 Rate 半星样式错乱问题

---

packages/react-vant/src/components/input/style/index.less

fix: 修复 Input 清除按钮在umi框架下不显示问题

---

packages/react-vant/src/components/datetime-picker/DatePicker.tsx

fix: 修复 DatetimePicker 的maxDate、minDate 没正常更新的问题

---

packages/react-vant/src/components/image-preview/ImagePreview.tsx
packages/react-vant/src/components/image-preview/slides.tsx

fix: 修复 ImagePreview 无法动态设置 startPosition 的问题

---

packages/react-vant/src/components/form/README.md

Update Form.Item Props README.md

Update Form README.md

---

packages/react-vant/src/components/overlay/README.md

修复`overlay遮罩层demo2（嵌入内容）`点击遮罩区无法关闭的问题

fix: 修复`overlay遮罩层demo2`关闭

---

packages/react-vant/src/components/uploader/PropsType.ts
packages/react-vant/src/components/uploader/README.md
packages/react-vant/src/components/uploader/Uploader.tsx
packages/react-vant/src/components/uploader/UploaderPreviewItem.tsx

feat: `Uploader` 支持手动指定是否为图片 #576

---

packages/react-vant/src/components/index-bar/IndexBar.tsx
packages/react-vant/src/components/index-bar/PropsType.ts
packages/react-vant/src/components/index-bar/README.md

- 修复 `stickyOffsetTop` 在 `sticky` 关闭时丢失值问题

feat: `IndexBar` 支持自定义右侧单个字符

---

packages/react-vant/src/components/button/Button.tsx
packages/react-vant/src/components/button/ButtonGroup.tsx
packages/react-vant/src/components/uploader/UploaderPreviewItem.tsx

1. 参数 "e" 隐式具有 "any" 类型，但可以从用法中推断出更好的类型，并且看到其他组件的click事件似乎有加上类型。
2. 优化一下嵌套的条件

fix: add button type & optimize condition

---

packages/react-vant/src/components/dropdown-menu/DropdownMenu.tsx
packages/react-vant/src/components/dropdown-menu/DropdownMenuItem.tsx
packages/react-vant/src/components/dropdown-menu/PropsType.ts
packages/react-vant/src/components/dropdown-menu/README.md

feat: dropdownMenu自定义选项的选中态勾选icon

---

packages/react-vant/src/components/tabs/Tabs.tsx

fix: tabs传入style(#595)

---

packages/react-vant-icons/gulpfile.js
packages/react-vant-icons/package.json
packages/react-vant-icons/src/icons/IconBase.tsx
packages/react-vant-icons/src/icons/createFromIconfontCN.tsx
packages/react-vant/package.json
packages/react-vant/src/components/button/Button.tsx
packages/react-vant/src/components/button/ButtonGroup.tsx
packages/react-vant/src/components/calendar/Calendar.tsx
packages/react-vant/src/components/calendar/style/index.less
packages/react-vant/src/components/collapse/Collapse.tsx
packages/react-vant/src/components/datetime-picker/DatePicker.tsx
packages/react-vant/src/components/dropdown-menu/DropdownMenu.tsx
packages/react-vant/src/components/dropdown-menu/DropdownMenuItem.tsx
packages/react-vant/src/components/dropdown-menu/PropsType.ts
packages/react-vant/src/components/dropdown-menu/README.md
packages/react-vant/src/components/list/LoadMore.tsx
packages/react-vant/src/components/number-keyboard/demo/base.tsx
packages/react-vant/src/components/number-keyboard/demo/control.tsx
packages/react-vant/src/components/popup/demo/base.tsx
packages/react-vant/src/components/stepper/PropsType.ts
packages/react-vant/src/components/stepper/README.md
packages/react-vant/src/components/stepper/Stepper.tsx
packages/react-vant/src/components/stepper/index.ts
packages/react-vant/src/components/tabs/Tabs.tsx
packages/react-vant/src/components/uploader/UploaderPreviewItem.tsx

feat: Fix Calendar/horizontal based on #592

---

packages/react-vant-icons/gulpfile.js
packages/react-vant-icons/package.json
packages/react-vant-icons/src/icons/IconBase.tsx
packages/react-vant-icons/src/icons/createFromIconfontCN.tsx
packages/react-vant/package.json
packages/react-vant/src/components/button/Button.tsx
packages/react-vant/src/components/button/ButtonGroup.tsx
packages/react-vant/src/components/calendar/Calendar.tsx
packages/react-vant/src/components/calendar/PropsType.ts
packages/react-vant/src/components/calendar/demo/custom.tsx
packages/react-vant/src/components/calendar/style/index.less
packages/react-vant/src/components/collapse/Collapse.tsx
packages/react-vant/src/components/datetime-picker/DatePicker.tsx
packages/react-vant/src/components/dropdown-menu/DropdownMenu.tsx
packages/react-vant/src/components/dropdown-menu/DropdownMenuItem.tsx
packages/react-vant/src/components/dropdown-menu/PropsType.ts
packages/react-vant/src/components/dropdown-menu/README.md
packages/react-vant/src/components/list/LoadMore.tsx
packages/react-vant/src/components/number-keyboard/demo/base.tsx
packages/react-vant/src/components/number-keyboard/demo/control.tsx
packages/react-vant/src/components/popup/demo/base.tsx
packages/react-vant/src/components/stepper/PropsType.ts
packages/react-vant/src/components/stepper/README.md
packages/react-vant/src/components/stepper/Stepper.tsx
packages/react-vant/src/components/stepper/index.ts
packages/react-vant/src/components/tabs/Tabs.tsx
packages/react-vant/src/components/uploader/UploaderPreviewItem.tsx

feat(Calendar): add `horizontal` feature

---

packages/react-vant/src/components/cell/Cell.tsx
packages/react-vant/src/components/field/Field.tsx

fix: fix bug for field and cell(#660)

---

packages/react-vant/src/components/calendar/PropsType.ts

fix: calendar value type

---

packages/react-vant/src/components/picker/PropsType.ts

should support number type in the demo link
[picker#基础用法](https://react-vant.3lang.dev/components/picker#%E5%9F%BA%E7%A1%80%E7%94%A8%E6%B3%95)

should support number type

---

packages/react-vant/src/components/picker/PropsType.ts

itemHeight should support string type

itemHeight should support string type

---

packages/react-vant/src/components/selector/README.md

change --rv-selector-checkedborder 
to --rv-selector-checked-border

fix selector-checked-border css api-props
