3lang3/react-vant

src/popup/index.tsx
Preact与React在对组件style以及useEffect与setState间的处理存在些许差异，导致Popup组件中的display无法被正确设置，通过些许调整可两边都兼容。望采纳！
BTW，我很喜欢你的这个库，尤其配合Preact做移动端App非常适合。
=> fix: popup compatibility with preact

src/stepper/index.tsx
Stepper组件的onBlur会触发onChange，但是它又没有维护好preValue，导致在输入框有焦点时点击 + - 状态会不对。
另外Stepper在onInput里触发onChange会感觉太频繁了，没有必要，onBlur时触发就挺好。在我们的业务中每次onChange需要去调用一个API，如果太频繁了会影响功能与性能，当然我们也可以自己throttle，但始终还是觉得如果Stepper不那么频繁触发onChange会更好，因此这个PR里把onInput中的onChange触发去掉了。望采纳！
=> fix: stepper oninput and onblue conflict

src/image/index.tsx
问题：
Image组件，图片正在加载的过程中组件被unmount，onLoad等事件回来后还是会set state，这会导致react报warning。现有代码中有mountedRef来跟踪组件的mounted情况，但是并没有被正确设置以及使用。
解决方法：
正确设置并使用mountedRef来避免问题。
=> fix: set state in image events

package.json, src/toast/PropsType.ts, src/toast/index.tsx, src/utils/base.ts
问题：
第二次调用Toast会发现它的onClose调用了两遍，问题在于在`useEffect`中将`internalAfterClose` push到了待下次显示时会调用的队列，但是BaseToast本身的onClose也会执行`internalAfterClose`。
解决方案：
首先保证internalAfterClose函数不会每次都变化，其次，通过保证其只执行一次可以回避在不同时机被两次调用的问题。
=> fix: toast onClose may be called twice

package.json, src/image/index.tsx
问题：
如果给Image的是一个data url，那么它的onLoad会先于props.src的变化执行，导致loading设置出错。
解决方案：
对于data url不需要设置loading为true。
=> fix: no loading if image src is a data url

package.json, src/image/Image.tsx
图片有缓存的情况下`onLoad`会很快触发，有时会先于`src`变化的effect，用`useLayoutEffect`可以保证执行的顺序。
=> fix: ensure correct image onload calling order

packages/react-vant/src/popup/style/index.less
`title`大部分情况下应该是居中的，可以自定义位置
本次PR中ws 对less文件提示报错，没用过`stylelintrc`，定位不出报错原因🙈
=> style(Popup): center the title

packages/react-vant/src/hooks/use-form-smart.ts
增加一个form hook
主要实现如下功能
- 简化原有的form调用方式
- 数据的初始化逻辑调整为 当value为空时不设置表单初始值. 便于从服务器拉取的值在initialValues初始化时未设置需要手动设置
- 增加数据双向同步,每次value变化时 自动设置表单
=> feat: add use-form-smart

packages/react-vant/src/index.ts
before
after
其他组件非default的type类型也有同样问题，包括引入hook也有出现，除此之外，还有没更好的方法去解决
=> fix(type) : fix export type from Uploader

packages/react-vant/src/field/README.md
**修正 autosize 示例无法自适应问题**
[文档示例](https://3lang3.github.io/react-vant/#/zh-CN/field) 中的 autosize 示例无法自动适应内容高度，需要改写为受控组件。
**修正 showWordLimit 示例当前字数一直为 0 问题**
同上，改写为受控组件恢复正常。
**修正 onChnage 的 api 介绍**
onChange 的介绍和 onFocus  介绍重复
=> docs(field): 修正 field 组件的文档错误

packages/react-vant/src/components/picker/Picker.tsx
=> fix: Picker 级联选择模式下children为空时渲染异常

packages/react-vant/src/components/search/PropsType.ts, packages/react-vant/src/components/search/README.md, packages/react-vant/src/components/search/Search.tsx
=> feat: `Search` 新增 `action` 用于自定义右侧操作内容 #580

packages/react-vant/src/components/dropdown-menu/DropdownMenu.tsx
当子组件props改变的时候，先执行的dropdown-menu组件，再执行方法
```ts
useImperativeHandle(ref, () => ({
toggle,
renderTitle,
state,
titleClass: props.titleClass,
disabled: props.disabled,
name: props.name,
options: props.options,
}))
```
=> fix: issues/599

packages/react-vant/src/components/checkbox/Checker.tsx
Fix #524 
Thanks to #526 , this pr let Checker recognize the forwarded `style` prop
=> fix(v2): checker add style

packages/react-vant/src/components/tabs/Tabs.tsx
Fix #550 
`react-activation` set display none for child elements, that causes line transition stops calculate.
In this PR, line transition does calculate by `useUpdateEffect()` after `react-activation` re-shows child elements on mount.
Also fix a potential bug of `type` toggle.
Reproduction: https://stackblitz.com/edit/vitejs-vite-umbtuh
Steps to reproduce: 
- npm i && npm dev
- Click the toggler button at the top
- Then see indicator stucks.
=> fix(tabs): line indicator transition bug (#550)

packages/react-vant/src/components/input/Input.tsx, packages/react-vant/src/components/text-area/TextArea.tsx
fix: #628 
- Input
- TextArea
预输入时不限制长度，并在结束时重新处理
=> fix(Input): ignore value check during composition

packages/react-vant/src/components/floating-panel/FloatingPanel.tsx, packages/react-vant/src/components/hooks/use-touch.ts
iOS: if touch events triggered but touch direction not recognized by `getDirection`, then 
1. FloatingPanel(FP) treat this touch as dragging and prevent it.
2. Until direction recognized and we try to scroll content, FP think it is not dragging then expectedly ignore
3. But the first touch move event is prevented, subsequent events are not active for content scrolling.
Reproduction: 
https://react-vant-pr-627.surge.sh/~demo/components/floating-panel 
1. Scroll panel to max anchor
2. Try scroll content
3. Get stuck sometimes.
=> fix(FloatingPanel): fix stuck during indetermine direction

packages/react-vant/src/components/image/Image.tsx
Image组件中，width，height，radius属性由于useMemo((...)=>{},[props.style])的原因，均不能动态修改
=> fix: image样式属性监听

packages/react-vant/src/components/sticky/Sticky.tsx
- `Sticky` 组件在调用时，需要动态更新`offset`的值，此时传入的`props.offsetTop`/`props.offsetBottom` 已经更新，但是由于 `useEventListener` 没有设置 `depends` 更新注册的回调，导致某些不为window且传入offsetTop的container fixed定位判断不准。
- 修改后，通过传入依赖触发 `useEffect` , 更新 `add` 方法， add方法内重新注册新的 `listener` 回调，拿到新的 offset值，问题修复。
=> fix(Sticky): 修复offsetTop通过 props传入时动态更新后，onScroll方法取offset仍为初始值的问题

packages/react-vant/src/components/tabs/Tabs.tsx
在 vant 以及 antd 等组件中，初始化 tab 组件后，选中下划线会直接定位到选中的 tab 下面：
而在 react-vant 中，选中下划线会从最左面移到选中 tab 下面，与 vant 交互不一致，看起来像是过早展现并加载了下划线的动画。
该 PR 修复了这个问题，让 react-vant 的 tab 选中下划线的交互和 vant 等主流移动端组件库一致。
cc @3lang3
=> fix(tabs): 修复 tabs 组件选中下划线在初始化时会从最左面移到目标位置的问题

packages/react-vant/src/components/datetime-picker/DatePicker.tsx
之前是默认显示的最小时间：
大多数情况应该是显示当前时间更方便。
修改后：
=> fix(datetime-picker): datetime-picker 没有值时，弹出层默认选中当前日期/时间。

packages/react-vant/src/components/form/demo/rules.tsx
文档中原示例代码的正则表达式作用是匹配前几位数字，一但数字超过后，将不再限制，可能产生歧义。（刚开始我还以为验证通过后不再触发验证：D）
=> fix(demo): 表单组件正则表达式验证示例与实际说明不符

packages/react-vant/src/components/datetime-picker/DatePicker.tsx
将默认的最小日期最大日期改用常量，修复当未设置最小日期/最大日期时，在每个渲染周期都使用新的Date对象，导致下段代码异常重复执行，而引起 confirm 时 value 不正确（fix #663 ）：
```
useUpdateEffect(() => {
const nextValue = formatValue(value)
if (nextValue && nextValue.valueOf() !== currentDate?.valueOf()) {
setCurrentDate(nextValue)
}
}, [value, filter, minDate, maxDate])
```
=> fix(datetime-picker): 默认最小日期最大日期使用常量；

packages/react-vant/package.json
#670  新增对locale的类型提示  但是仍不支持文档中国际化的import enUS from 'react-vant/es/locale/lang/en-US';
期望能把export 这个字段删除 但是会造成break change 也可以把文档修改下 其实import  {enUs} from 'react-vant' 即可
=> feat:新增import locale 类型提示

packages/react-vant/src/components/picker/Picker.tsx, packages/react-vant/src/components/toast/method.tsx
修复 Picker 在 ios 下通过 from.setFieldValue 设置 value 后第一次弹出没有选中对应 value 的问题
=> 修复 Picker 在 ios 下通过 from.setFieldValue 设置 value 后第一次弹出没有选中对应 value 的问题

packages/react-vant/src/components/popover/Popover.tsx, packages/react-vant/src/components/popover/PropsType.ts, packages/react-vant/src/components/popover/README.md
Popover supports controlling visibility by visible props
#709
=> feat: popover add visible props

packages/react-vant/src/components/uploader/README.md
在react-vant的文档里upload中的Event配置没有正常显示，排查发现markdown的编写存在bug，故修复
=> 修复upload中markdown的错误格式，导致Event的配置未能正常显示

packages/react-vant/src/components/image-preview/ImagePreview.tsx, packages/react-vant/src/components/image-preview/slide.tsx, packages/react-vant/src/components/image-preview/slides.tsx, pnpm-lock.yaml
Add LazyLoad component to component ImagePreview/Slide
=> fix:  bug #678

packages/react-vant-icons/package.json
Fixed the ts type error in react caused by @type/react in the new version
=> fix: build icon type error

packages/react-vant/src/components/utils/format/number.ts
复制 如 1-1-1的数字，到input type="digit"，处理格式有误。期望是 1-1-1  -> 111，但实际时 1-1-1 -> 11-1
=> fix(input): 修复 复制包含多个'-'的数字到input type=digit 时，格式错误

packages/react-vant/src/components/dialog/method.tsx
原 `Dialog.show` 方法调用返回的 `destory` 方法固定为 `noop`，不能按照预期行为工作:
调用 `Dialog.show` 时，`return` 的执行会优先于 `TempDialog` 组件中方法的执行。原 destory 为基础类型，无法在调用时获取到最新的期望内容。
用 `Map` 存储 id-close 方法键值对，因为 `Map` 是引用类型，故在使用方调用时，能根据 id 拿到最新且对应的销毁方法。
其中 id 为 `rv-dialog-root--${Date.now()}`，实际业务中可保证基本唯一。
具体代码见 PR。
=> fix: dialog.show method return close function

packages/react-vant/src/components/datetime-picker/README.md
| cancelButtonText | 取消按钮文字 | _ReactNode_ | `取消` |
=> string -> _ReactNode_
